infrastructure: base: opensearch: opensearch_dashboards: Fix config.
This commit follows c277fae3ede679980363a8018503fd218795bde7.

Fixes the error:

    FATAL Error: [config validation of [data].search.usageTelemetry]:
    definition for this key is missing