wigust: Downgrade calamares.
Downgrade because of:

CMakeFiles/geoiptest.dir/GeoIPTests.cpp.o: In function `GeoIPTests::testJSON()':
GeoIPTests.cpp:(.text+0x4f3): undefined reference to `bool QTest::qCompare<QString, char [8]>(QString const&, char const (&) [8], char const*, char const*, char const*, int)'
collect2: error: ld returned 1 exit status

* wigust/packages/calamares.scm (calamares): Downgrade.