Revert "infrastructure: cluster1: windows: Add PVC template."
This reverts commit 7ffc66b7a42946990ad475de66e82685bf00d313.

windows 172d False
VirtualMachineInstanceReplicaSet/windows/vm-windows-datavolume dry-run failed,
error: failed to create typed patch object (windows/vm-windows-datavolume;
kubevirt.io/v1, Kind=VirtualMachineInstanceReplicaSet):
.spec.dataVolumeTemplates: field not declared in schema...