Revert "apps: base: mitmproxy: Enable tty for mitmproxy container."
This reverts commit 5df2bcb0eb5582598b8d932b56a1eb7fcbcde413.

'tty' with 'true' produces an error:

    $ kubectl -n mitmproxy logs --all-containers -l app.kubernetes.io/name=mitmproxy
                                                     ^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/lib/python3.11/textwrap.py", line 384, in wrap
        return w.wrap(text)
               ^^^^^^^^^^^^
      File "/usr/local/lib/python3.11/textwrap.py", line 359, in wrap
        return self._wrap_chunks(chunks)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/lib/python3.11/textwrap.py", line 253, in _wrap_chunks
        raise ValueError("invalid width %r (must be > 0)" % self.width)
    ValueError: invalid width 0 (must be > 0)